import React from 'react';
import { View, Text, ScrollView, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Card } from '../../src/components/ui';

export default function LegalScreen() {
    const router = useRouter();
    const { type } = useLocalSearchParams<{ type: 'terms' | 'privacy' }>();

    const title = type === 'privacy' ? 'Privacy Policy' : 'Terms of Service';

    return (
        <SafeAreaView className="flex-1 bg-background-secondary dark:bg-dark-primary">
            {/* Header */}
            <View className="flex-row items-center px-4 py-3 border-b border-border-light dark:border-dark-tertiary bg-background-primary dark:bg-dark-card">
                <TouchableOpacity
                    onPress={() => router.back()}
                    className="mr-3"
                >
                    <Ionicons name="arrow-back" size={24} color="#64748b" />
                </TouchableOpacity>
                <Text className="text-xl font-bold text-text-primary dark:text-text-inverse">{title}</Text>
            </View>

            <ScrollView contentContainerStyle={{ padding: 16 }}>
                <Card variant="elevated" padding="lg">
                    <Text className="text-sm text-text-secondary dark:text-gray-400 leading-6 mb-4">
                        Last updated: January 15, 2026
                    </Text>

                    {type === 'terms' ? (
                        <>
                            <Text className="text-lg font-bold text-text-primary dark:text-text-inverse mb-2">1. Acceptance of Terms</Text>
                            <Text className="text-base text-text-secondary dark:text-gray-400 leading-6 mb-6">
                                By accessing and using Art Agent, you accept and agree to be bound by the terms and provision of this agreement.
                            </Text>

                            <Text className="text-lg font-bold text-text-primary dark:text-text-inverse mb-2">2. Use License</Text>
                            <Text className="text-base text-text-secondary dark:text-gray-400 leading-6 mb-6">
                                Permission is granted to temporarily download one copy of the materials (information or software) on Art Agent's website for personal, non-commercial transitory viewing only.
                            </Text>

                            <Text className="text-lg font-bold text-text-primary dark:text-text-inverse mb-2">3. Verification</Text>
                            <Text className="text-base text-text-secondary dark:text-gray-400 leading-6 mb-6">
                                Artists guarantee that all uploaded work is their own creation and not generated by AI, unless explicitly categorized as such.
                            </Text>
                        </>
                    ) : (
                        <>
                            <Text className="text-lg font-bold text-text-primary dark:text-text-inverse mb-2">1. Data Collection</Text>
                            <Text className="text-base text-text-secondary dark:text-gray-400 leading-6 mb-6">
                                We collect information you provide directly to us, such as when you create an account, update your profile, or communicate with us.
                            </Text>

                            <Text className="text-lg font-bold text-text-primary dark:text-text-inverse mb-2">2. Use of Information</Text>
                            <Text className="text-base text-text-secondary dark:text-gray-400 leading-6 mb-6">
                                We use the information we collect to operate, maintain, and improve our services, including to verify identities and prevent fraud.
                            </Text>

                            <Text className="text-lg font-bold text-text-primary dark:text-text-inverse mb-2">3. Data Security</Text>
                            <Text className="text-base text-text-secondary dark:text-gray-400 leading-6 mb-6">
                                We implement a variety of security measures to maintain the safety of your personal information when you access your personal data.
                            </Text>
                        </>
                    )}
                </Card>
            </ScrollView>
        </SafeAreaView>
    );
}
